version: '3.8'

services: 
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "example_db"
    ports:
    - "3306:3308"
    volumes:
    - db-config:/etc/mysql
    - db-data:/var/lib/mysql
    - ./db/backup/files/:/data_backup/data
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: node-mysql-app
    ports:
      - "3000:3200"
    volumes: 
      - ./app:/app
      - app/node_modules
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true

volumes: 
  db-config:
  db-data: